-- MySQL Script generated by MySQL Workbench
-- 05/13/15 16:10:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proyectoWEB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyectoWEB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyectoWEB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `proyectoWEB` ;

-- -----------------------------------------------------
-- Table `proyectoWEB`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectoWEB`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `admin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectoWEB`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectoWEB`.`categoria` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectoWEB`.`consola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectoWEB`.`consola` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectoWEB`.`juegos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectoWEB`.`juegos` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `cantidad` INT NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `categoria_id` INT NULL,
  `consola_id` INT NOT NULL,
  PRIMARY KEY (`id`, `categoria_id`, `consola_id`),
  INDEX `fk_juegos_categoria1_idx` (`categoria_id` ASC),
  INDEX `fk_juegos_consola1_idx` (`consola_id` ASC),
  CONSTRAINT `fk_juegos_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `proyectoWEB`.`categoria` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_juegos_consola1`
    FOREIGN KEY (`consola_id`)
    REFERENCES `proyectoWEB`.`consola` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectoWEB`.`usuarios_has_juegos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectoWEB`.`usuarios_has_juegos` (
  `usuarios_id` INT NOT NULL,
  `juegos_id` INT NOT NULL,
  `cantidad` VARCHAR(45) NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`usuarios_id`, `juegos_id`),
  INDEX `fk_usuarios_has_juegos_juegos1_idx` (`juegos_id` ASC),
  INDEX `fk_usuarios_has_juegos_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_usuarios_has_juegos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `proyectoWEB`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuarios_has_juegos_juegos1`
    FOREIGN KEY (`juegos_id`)
    REFERENCES `proyectoWEB`.`juegos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `proyectoWEB`.`usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `proyectoWEB`;
INSERT INTO `proyectoWEB`.`usuarios` (`id`, `name`, `apellido`, `email`, `password`, `admin`) VALUES (1, 'admin', 'admin', 'admin@hotmail.com', 'adminadmin', true);
INSERT INTO `proyectoWEB`.`usuarios` (`id`, `name`, `apellido`, `email`, `password`, `admin`) VALUES (2, 'cliente', 'cliente', 'cliente@hotmail.com', 'cliente123', false);

COMMIT;


-- -----------------------------------------------------
-- Data for table `proyectoWEB`.`categoria`
-- -----------------------------------------------------
START TRANSACTION;
USE `proyectoWEB`;
INSERT INTO `proyectoWEB`.`categoria` (`id`, `nombre`) VALUES (1, 'LUCHA');
INSERT INTO `proyectoWEB`.`categoria` (`id`, `nombre`) VALUES (2, 'CARRERA');
INSERT INTO `proyectoWEB`.`categoria` (`id`, `nombre`) VALUES (3, 'DEPORTE');
INSERT INTO `proyectoWEB`.`categoria` (`id`, `nombre`) VALUES (4, 'ROL');
INSERT INTO `proyectoWEB`.`categoria` (`id`, `nombre`) VALUES (5, 'SHOOTER');

COMMIT;


-- -----------------------------------------------------
-- Data for table `proyectoWEB`.`consola`
-- -----------------------------------------------------
START TRANSACTION;
USE `proyectoWEB`;
INSERT INTO `proyectoWEB`.`consola` (`id`, `nombre`) VALUES (1, 'PLAY STATION 3');
INSERT INTO `proyectoWEB`.`consola` (`id`, `nombre`) VALUES (2, 'PLAY STATION 4');
INSERT INTO `proyectoWEB`.`consola` (`id`, `nombre`) VALUES (3, 'XBOX 360');
INSERT INTO `proyectoWEB`.`consola` (`id`, `nombre`) VALUES (4, 'XBOX ONE');
INSERT INTO `proyectoWEB`.`consola` (`id`, `nombre`) VALUES (5, 'WII');
INSERT INTO `proyectoWEB`.`consola` (`id`, `nombre`) VALUES (6, 'WII U');

COMMIT;


-- -----------------------------------------------------
-- Data for table `proyectoWEB`.`juegos`
-- -----------------------------------------------------
START TRANSACTION;
USE `proyectoWEB`;
INSERT INTO `proyectoWEB`.`juegos` (`id`, `nombre`, `precio`, `cantidad`, `imagen`, `categoria_id`, `consola_id`) VALUES (1, 'Mortal Kombat X', 799.99, 20, DEFAULT, 1, 4);
INSERT INTO `proyectoWEB`.`juegos` (`id`, `nombre`, `precio`, `cantidad`, `imagen`, `categoria_id`, `consola_id`) VALUES (2, 'Gears of War 3', 599.99, 40, DEFAULT, 5, 3);

COMMIT;

